package com.my_hourly.settings.workLogs.mapper;

import com.my_hourly.settings.workLogs.dto.request.WorkLogSettingsRequest;
import com.my_hourly.settings.workLogs.dto.response.WorkLogSettingsResponse;
import com.my_hourly.settings.workLogs.entity.WorkLogSettings;
import org.springframework.stereotype.Component;

@Component
public class WorkLogSettingsMapper {

    public WorkLogSettingsResponse toResponse(WorkLogSettings entity) {

        if (entity == null) {
            return null;
        }

        return WorkLogSettingsResponse.builder()
                .id(entity.getId())
                .workLogSubmissionRequired(entity.getWorkLogSubmissionRequired())
                .reportRequiredBeforeCheckout(entity.getReportRequiredBeforeCheckout())
                .reportSubmissionDeadline(entity.getReportSubmissionDeadline())
                .minimumWorkLogEntries(entity.getMinimumWorkLogEntries())
                .workLogReminderEnabled(entity.getWorkLogReminderEnabled())
                .reminderIntervalMinutes(entity.getReminderIntervalMinutes())
                .managerEmailNotification(entity.getManagerEmailNotification())
                .employeePdfDownloadAllowed(entity.getEmployeePdfDownloadAllowed())
                .managerApprovalRequired(entity.getManagerApprovalRequired())
                .allowWorkLogEditAfterSubmission(entity.getAllowWorkLogEditAfterSubmission())
                .autoGenerateDailySummary(entity.getAutoGenerateDailySummary())
                .minimumWorkLogDescriptionLength(entity.getMinimumWorkLogDescriptionLength())
                .allowMultipleReportSubmissionsPerDay(entity.getAllowMultipleReportSubmissionsPerDay())
                .active(entity.getActive())
                .build();
    }

    public void updateEntity(
            WorkLogSettingsRequest request,
            WorkLogSettings entity) {

        entity.setWorkLogSubmissionRequired(request.getWorkLogSubmissionRequired());
        entity.setReportRequiredBeforeCheckout(request.getReportRequiredBeforeCheckout());
        entity.setReportSubmissionDeadline(request.getReportSubmissionDeadline());
        entity.setMinimumWorkLogEntries(request.getMinimumWorkLogEntries());
        entity.setWorkLogReminderEnabled(request.getWorkLogReminderEnabled());
        entity.setReminderIntervalMinutes(request.getReminderIntervalMinutes());
        entity.setManagerEmailNotification(request.getManagerEmailNotification());
        entity.setEmployeePdfDownloadAllowed(request.getEmployeePdfDownloadAllowed());
        entity.setManagerApprovalRequired(request.getManagerApprovalRequired());
        entity.setAllowWorkLogEditAfterSubmission(request.getAllowWorkLogEditAfterSubmission());
        entity.setAutoGenerateDailySummary(request.getAutoGenerateDailySummary());
        entity.setMinimumWorkLogDescriptionLength(request.getMinimumWorkLogDescriptionLength());
        entity.setAllowMultipleReportSubmissionsPerDay(request.getAllowMultipleReportSubmissionsPerDay());
    }
}