spring.application.name=my_hourly
server.port=8081

# ==========================
# MySQL Configuration
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/MY_Hourly?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=nachiketh@10

# ==========================
# JPA Configuration
# ==========================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Remove this line (Hibernate detects it automatically)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect