
# ===============================
# PostgreSQL (Aiven)
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION}


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


#SMTP

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configure SMTP credentials per environment. The reset URL should point to the frontend reset-password page.
app.password-reset.token-expiration-minutes=${PASSWORD_RESET_EXPIRATION}
app.password-reset.frontend-url=${PASSWORD_RESET_FRONTEND_URL}
app.password-reset.from=${PASSWORD_RESET_EMAIL}


# application.properties
#cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
#cloudinary.api-key=${CLOUDINARY_API_KEY}
#cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#r2.endpoint=${R2_ENDPOINT}
#r2.bucket=${R2_BUCKET}
#r2.public-url=${R2_PUBLIC_URL}
#r2.access-key=${R2_ACCESS_KEY}
#r2.secret-key=${R2_SECRET_KEY}


# Backblaze B2 Storage Service
b2.bucket=${B2_BUCKET_NAME}
b2.access-key=${B2_ACCESS_KEY}
b2.secret-key=${B2_SECRET_KEY}
b2.endpoint=${B2_ENDPOINT}
b2.region=${B2_REGION}
b2.public-url=${B2_PUBLIC_URL}




