spring.application.name=my_hourly



spring.profiles.active=dev
server.port=${PORT:8080}

springdoc.swagger-ui.tagsSorter=alpha

# -----------------------------------------------
# Initial SUPER_ADMIN seed (DataInitializer)
# Change these BEFORE first run in production!
# -----------------------------------------------
app.super-admin.username=superadmin
app.super-admin.email=superadmin@myhourly.com
app.super-admin.password=Admin@1234

#app.manager.username=anagha
#app.manager.email=manager@myhourly.com
#app.manager.password=Manager@1234
#
#app.hr.username=harshitha
#app.hr.email=hr@myhourly.com
#app.hr.password=Hr@1234
