package com.my_hourly.settings.workLogs.dto.request;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.time.LocalTime;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WorkLogSettingsRequest {

    @NotNull
    private Boolean workLogSubmissionRequired;

    @NotNull
    private Boolean reportRequiredBeforeCheckout;

    @NotNull
    private LocalTime reportSubmissionDeadline;

    @NotNull
    @Min(1)
    private Integer minimumWorkLogEntries;

    @NotNull
    private Boolean workLogReminderEnabled;

    @NotNull
    private Integer reminderIntervalMinutes;

    @NotNull
    private Boolean managerEmailNotification;

    @NotNull
    private Boolean employeePdfDownloadAllowed;

    @NotNull
    private Boolean managerApprovalRequired;

    @NotNull
    private Boolean allowWorkLogEditAfterSubmission;

    @NotNull
    private Boolean autoGenerateDailySummary;

    @NotNull
    @Min(10)
    private Integer minimumWorkLogDescriptionLength;

    @NotNull
    private Boolean allowMultipleReportSubmissionsPerDay;

}
