package com.my_hourly.settings.workLogs.dto.request;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.time.LocalTime;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WorkLogSettingsRequest {

    @NotNull(message = "Work log submission required field is mandatory")
    private Boolean workLogSubmissionRequired;

    @NotNull(message = "Report required before checkout field is mandatory")
    private Boolean reportRequiredBeforeCheckout;

    @NotNull(message = "Report submission deadline is mandatory")
    @JsonFormat(pattern = "HH:mm:ss")
    private LocalTime reportSubmissionDeadline;

    @NotNull(message = "Minimum work log entries is mandatory")
    @Min(value = 1, message = "Minimum work log entries must be at least 1")
    private Integer minimumWorkLogEntries;

    @NotNull(message = "Work log reminder enabled field is mandatory")
    private Boolean workLogReminderEnabled;

    @NotNull(message = "Reminder interval minutes is mandatory")
    @Min(value = 1, message = "Reminder interval minutes must be at least 1")
    private Integer reminderIntervalMinutes;

    @NotNull(message = "Manager email notification field is mandatory")
    private Boolean managerEmailNotification;

    @NotNull(message = "Employee PDF download permission field is mandatory")
    private Boolean employeePdfDownloadAllowed;

    @NotNull(message = "Manager approval required field is mandatory")
    private Boolean managerApprovalRequired;

    @NotNull(message = "Allow work log edit after submission field is mandatory")
    private Boolean allowWorkLogEditAfterSubmission;

    @NotNull(message = "Auto generate daily summary field is mandatory")
    private Boolean autoGenerateDailySummary;

    @NotNull(message = "Minimum work log description length is mandatory")
    @Min(value = 10, message = "Minimum work log description length must be at least 10 characters")
    private Integer minimumWorkLogDescriptionLength;

    @NotNull(message = "Allow multiple report submissions per day field is mandatory")
    private Boolean allowMultipleReportSubmissionsPerDay;

}