package com.my_hourly.common.enums;

public enum ErrorCode {

    // Authentication
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    UNAUTHORIZED,

    // Employee
    EMPLOYEE_NOT_FOUND,
    EMPLOYEE_ALREADY_EXISTS,

    // Organization
    COMPANY_NOT_FOUND,
    DEPARTMENT_NOT_FOUND,
    DESIGNATION_NOT_FOUND,

    // Attendance
    ATTENDANCE_ALREADY_EXISTS,
    INVALID_ATTENDANCE,

    // Leave
    LEAVE_NOT_FOUND,
    LEAVE_BALANCE_EXCEEDED,

    // Payroll
    PAYROLL_ALREADY_PROCESSED,

    // Validation
    VALIDATION_FAILED,

    // Generic
    RESOURCE_NOT_FOUND,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRED,
    INTERNAL_SERVER_ERROR, INVALID_PASSWORD, PASSWORD_MISMATCH,

    PASSWORD_ALREADY_IN_USE,

    // User management
    USER_ALREADY_EXISTS,
    ROLE_NOT_FOUND,
    ROLE_ALREADY_ASSIGNED,
    NOT_ALLOWED, LEAVE_ALREADY_EXIST, INSUFFICIENT, APPROVAL_PENDING, REPORTING_MANAGER_NOT_ASSIGNED, LEAVE_ALREADY_PROCESSED, INVALID_DATE, REASON_REQUIRED, INVALID_REQUEST, LEAVE_ALREADY_CANCELLED, BAD_REQUEST, USER_NOT_FOUND, ON_LEAVE, ROLE_NOT_ASSIGNED
}
