package com.my_hourly.common.enums;

public enum ErrorCode {

    // Authentication
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    UNAUTHORIZED,

    // Employee
    EMPLOYEE_NOT_FOUND,
    EMPLOYEE_ALREADY_EXISTS,

    // Organization
    COMPANY_NOT_FOUND,
    DEPARTMENT_NOT_FOUND,
    DESIGNATION_NOT_FOUND,

    // Attendance
    ATTENDANCE_ALREADY_EXISTS,
    INVALID_ATTENDANCE,

    // Leave
    LEAVE_NOT_FOUND,
    LEAVE_BALANCE_EXCEEDED,

    // Payroll
    PAYROLL_ALREADY_PROCESSED,

    // Validation
    VALIDATION_FAILED,

    // Generic
    RESOURCE_NOT_FOUND,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRED,
    INTERNAL_SERVER_ERROR, INVALID_PASSWORD, PASSWORD_MISMATCH, INVALID_PASSWORD_RESET_TOKEN,

    PASSWORD_ALREADY_IN_USE,

    // Attendance Regularization
    REGULARIZATION_NOT_FOUND,
    REGULARIZATION_DETAIL_NOT_FOUND,
    ATTENDANCE_NOT_FOUND,
    ATTENDANCE_BELONGS_TO_ANOTHER_EMPLOYEE,
    ATTENDANCE_DATE_OUT_OF_RANGE,
    INVALID_STATUS_TRANSITION,
    DUPLICATE_ACTIVE_REGULARIZATION,
    REGULARIZATION_NOT_PENDING,
    DETAIL_NOT_PENDING,
    MANAGER_NOT_AUTHORIZED,
    REGULARIZATION_DETAIL_STATE_CHANGED,
    REGULARIZATION_ALREADY_APPROVED,
    REGULARIZATION_HAS_ACTIVE_REGULARIZATION,
    CANNOT_REVERT,

    // User management
    USER_ALREADY_EXISTS,
    ROLE_NOT_FOUND,
    ROLE_ALREADY_ASSIGNED,
    NOT_ALLOWED, LEAVE_ALREADY_EXIST, INSUFFICIENT, APPROVAL_PENDING, REPORTING_MANAGER_NOT_ASSIGNED, LEAVE_ALREADY_PROCESSED, INVALID_DATE, REASON_REQUIRED, INVALID_REQUEST, LEAVE_ALREADY_CANCELLED, BAD_REQUEST, USER_NOT_FOUND, ON_LEAVE, HOLIDAY_DAY, PERFORMANCE_REVIEW_ALREADY_EXIST, SALARY_TEMPLATE_ALREADY_PRESENT, ROLE_NOT_ASSIGNED
}
