package com.my_hourly.settings.workLogs.entity;

// DISABLED: The whole workLogs settings submodule is unused.
// - SettingController /work-log endpoints are commented out.
// - No other module references WorkLogSettings, its repository, service or DTOs.
// - Its only writer was DataInitializer.seedWorkLogSettings() (also disabled).
// Re-enable the submodule here and in SettingController / DataInitializer if needed.
//
//import com.my_hourly.settings.BaseSettings;
//import jakarta.persistence.Column;
//import jakarta.persistence.Entity;
//import jakarta.persistence.Table;
//import lombok.*;
//
//import java.time.LocalTime;
//
//@Entity
//@Table(name = "work_log_settings")
//@Getter
//@Setter
//@Builder
//@NoArgsConstructor
//@AllArgsConstructor
//public class WorkLogSettings extends BaseSettings {
//
//    @Column(nullable = false)
//    private Boolean workLogSubmissionRequired;
//
//    @Column(nullable = false)
//    private Boolean reportRequiredBeforeCheckout;
//
//    @Column(nullable = false)
//    private LocalTime reportSubmissionDeadline;
//
//    @Column(nullable = false)
//    private Integer minimumWorkLogEntries;
//
//    @Column(nullable = false)
//    private Boolean workLogReminderEnabled;
//
//    @Column(nullable = false)
//    private Integer reminderIntervalMinutes;
//
//    @Column(nullable = false)
//    private Boolean managerEmailNotification;
//
//    @Column(nullable = false)
//    private Boolean employeePdfDownloadAllowed;
//
//    @Column(nullable =false)
//    private Boolean managerApprovalRequired;
//
//    @Column(nullable = false)
//    private Boolean allowWorkLogEditAfterSubmission;
//
//    @Column(nullable = false)
//    private Boolean autoGenerateDailySummary;
//
//    @Column(nullable = false)
//    private Integer minimumWorkLogDescriptionLength;
//
//    @Column(nullable = false)
//    private Boolean allowMultipleReportSubmissionsPerDay;
//
//    @Column(nullable = false)
//    private Boolean active;
//}
