-- =====================================================================
-- V10 - Per-calendar-month PAID attribution for leave requests
-- =====================================================================
-- V9 stored one paid_days / lop_days pair per request. That is enough to
-- classify a single-month request, but NOT enough to answer "how many PAID
-- days were taken in calendar month M?": a request that spans a month
-- boundary had all of its paid_days attributed to the request's startDate
-- month by LeaveRequestRepository#sumPaidLeaveDaysInMonth, so a later
-- approval in the second month could spend an allowance that was already
-- spent (and the month-end expiry report mis-attributed usage the same way).
--
-- This table stores the classifier's per-month breakdown at approval time:
-- one row per (request, calendar month) with the PAID days and the working
-- days that fell in that month. Usage queries then sum by allocation_month -
-- a leave day is counted in the month it actually falls in, exactly once.
--
-- Rows are written only when a request is approved (paid leave types), and a
-- request can only be approved once (row lock + PENDING status check in
-- LeaveRequestServiceImpl#managerAction), so no day is ever double-counted.
--
-- Historical requests approved before this migration have no allocation rows;
-- the usage queries fall back to the legacy start-date attribution for them
-- (see the NOT EXISTS branches in LeaveRequestRepository). Their true
-- per-month split is unrecoverable - only the aggregate paid/total existed.
--
-- ON DELETE CASCADE: leave types are hard-deleted through a JPQL bulk delete
-- of leave_requests, which bypasses JPA cascades, so referential integrity for
-- those deletions is enforced by the database itself.
--
-- All statements are idempotent so this script is safe to replay.
-- =====================================================================

create table if not exists leave_request_month_allocations (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    leave_request_id bigint not null,
    allocation_month date not null,
    paid_days integer not null,
    working_days integer not null,
    primary key (id),
    constraint uq_leave_request_month_allocations
        unique (leave_request_id, allocation_month)
);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_leave_request_month_allocations_request'
    ) then
        alter table leave_request_month_allocations
            add constraint fk_leave_request_month_allocations_request
            foreign key (leave_request_id)
            references leave_requests
            on delete cascade;
    end if;
end
$$;

-- The monthly usage queries filter on the month first, then join back to
-- leave_requests for employee / status.
create index if not exists idx_leave_request_month_allocations_month
    on leave_request_month_allocations (allocation_month);
