-- =====================================================================
-- V1 - Baseline schema
-- =====================================================================
-- Machine-generated from the JPA entities (Hibernate schema export) and
-- committed as the Flyway baseline.
--
-- Existing databases are baselined at version 1 (see spring.flyway.
-- baseline-on-migrate), so this script is skipped there. It only runs
-- against an empty schema (new local/CI database) to create everything.
--
-- Never edit this file. Add V2, V3, ... for every schema change.
-- =====================================================================

create table announcement_attachment_urls (
    announcement_id bigint not null,
    attachment_url varchar(1000)
);

create table announcements (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    title varchar(150) not null,
    message varchar(1000) not null,
    upload_type varchar(255) check ((upload_type in ('MAGAZINE','POST'))),
    primary key (id)
);

create table attendance (
    attendance_date date not null,
    check_in_latitude numeric(10,7),
    check_in_longitude numeric(10,7),
    check_out_latitude numeric(10,7),
    check_out_longitude numeric(10,7),
    early_exit_minutes integer not null,
    late_minutes integer not null,
    overtime_minutes integer not null,
    total_break_minutes integer,
    working_minutes integer,
    check_in_time timestamp(6),
    check_out_time timestamp(6),
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    attendance_status varchar(255) check ((attendance_status in ('PRESENT','LATE','HALF_DAY','ABSENT','LEAVE','HOLIDAY','WEEKEND','MISSED_CHECKOUT'))),
    employee_status varchar(255) check ((employee_status in ('WORKING','ON_BREAK','CHECKED_OUT'))),
    primary key (id)
);

create table attendance_breaks (
    break_minutes integer,
    attendance_id bigint not null,
    break_end_time timestamp(6),
    break_start_time timestamp(6) not null,
    id bigint generated by default as identity,
    break_type varchar(255) not null check ((break_type in ('LUNCH','TEA','PERSONAL','MEETING','NO_ACTIVE_BREAK','OTHER'))),
    primary key (id)
);

create table attendance_regularization (
    from_date date not null,
    to_date date not null,
    approved_at timestamp(6),
    approved_by bigint,
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    rejected_at timestamp(6),
    rejected_by bigint,
    requested_at timestamp(6),
    updated_at timestamp(6),
    status varchar(30) not null check ((status in ('PENDING','PARTIALLY_APPROVED','APPROVED','REJECTED','CANCELLED'))),
    reason varchar(500) not null,
    rejection_reason varchar(500),
    primary key (id)
);

create table attendance_regularization_detail (
    approved_check_in timestamp(6),
    approved_check_out timestamp(6),
    attendance_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    original_check_in timestamp(6),
    original_check_out timestamp(6),
    regularization_id bigint not null,
    requested_check_in timestamp(6),
    requested_check_out timestamp(6),
    updated_at timestamp(6),
    approved_status varchar(30) check ((approved_status in ('PRESENT','LATE','HALF_DAY','ABSENT','LEAVE','HOLIDAY','WEEKEND','MISSED_CHECKOUT'))),
    original_status varchar(30) not null check ((original_status in ('PRESENT','LATE','HALF_DAY','ABSENT','LEAVE','HOLIDAY','WEEKEND','MISSED_CHECKOUT'))),
    requested_status varchar(30) not null check ((requested_status in ('PRESENT','LATE','HALF_DAY','ABSENT','LEAVE','HOLIDAY','WEEKEND','MISSED_CHECKOUT'))),
    status varchar(30) not null check ((status in ('PENDING','APPROVED','REJECTED','REVERTED'))),
    remarks varchar(500),
    primary key (id)
);

create table attendance_settings (
    active boolean not null,
    checkout_cutoff_minutes integer not null,
    grace_period_minutes integer not null,
    half_day_working_minutes integer not null,
    holiday_attendance_allowed boolean not null,
    minimum_working_minutes integer not null,
    office_end_time time(0) not null,
    office_start_time time(0) not null,
    overtime_enabled boolean not null,
    weekend_attendance_allowed boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    primary key (id)
);

create table company_settings (
    active boolean not null,
    working_days_per_week integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    currency varchar(10) not null,
    phone_number varchar(20),
    postal_code varchar(20),
    company_code varchar(30) not null unique,
    time_zone varchar(50) not null,
    city varchar(100),
    country varchar(100),
    state varchar(100),
    company_name varchar(150) not null,
    email varchar(150) not null,
    website varchar(150),
    logo_url varchar(500),
    address_line1 varchar(255),
    address_line2 varchar(255),
    primary key (id)
);

create table departments (
    active boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    department_code varchar(20) not null unique,
    department_name varchar(100) not null,
    description varchar(255),
    primary key (id)
);

create table designations (
    active boolean not null,
    created_at timestamp(6) not null,
    department_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    description varchar(255),
    designation_code varchar(255) not null unique,
    designation_name varchar(255) not null,
    primary key (id)
);

create table employee_payment_details (
    created_at timestamp(6) not null,
    employee_id bigint not null unique,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    ifsc_code varchar(20) not null,
    pan_number varchar(20),
    account_number varchar(30) not null,
    esi_number varchar(30),
    payment_mode varchar(30) not null check ((payment_mode in ('BANK_TRANSFER','UPI','CHEQUE','CASH'))),
    pf_number varchar(30),
    uan_number varchar(30),
    bank_name varchar(100) not null,
    primary key (id)
);

create table employees (
    active boolean not null,
    date_of_birth date,
    date_of_joining date,
    created_at timestamp(6) not null,
    department_id bigint not null,
    designation_id bigint not null,
    id bigint generated by default as identity,
    job_title_id bigint not null,
    reporting_manager_id bigint,
    updated_at timestamp(6),
    user_id bigint not null unique,
    phone_number varchar(15) not null,
    first_name varchar(50) not null,
    last_name varchar(50),
    email varchar(255) not null unique,
    employee_code varchar(255) not null,
    employment_type varchar(255) not null check ((employment_type in ('FULL_TIME','PART_TIME','CONTRACT','INTERN'))),
    gender varchar(255) not null check ((gender in ('MALE','FEMALE'))),
    profile_photo_name varchar(255),
    profile_photo_type varchar(255),
    role_name varchar(255) not null check ((role_name in ('SUPER_ADMIN','HR_ADMIN','MANAGER','EMPLOYEE','PAYROLL_ADMIN','CLIENT'))),
    profile_photo oid,
    primary key (id)
);

create table holidays (
    active boolean not null,
    attendance_allowed boolean not null,
    holiday_date date not null,
    recurring boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    holiday_name varchar(100) not null,
    description varchar(300),
    holiday_type varchar(255) not null check ((holiday_type in ('HOLIDAY','PUBLIC_HOLIDAY','OPTIONAL_HOLIDAY','WEEKEND'))),
    primary key (id),
    unique (holiday_date)
);

create table job_titles (
    active boolean not null,
    created_at timestamp(6) not null,
    designation_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    job_title varchar(100) not null,
    job_title_code varchar(255) not null unique,
    primary key (id)
);

create table leave_approvals (
    approved_by bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    leave_request_id bigint not null,
    updated_at timestamp(6),
    remarks varchar(500),
    action varchar(255) not null check ((action in ('APPROVE','REJECT'))),
    approval_level varchar(255) not null check ((approval_level in ('MANAGER','HR'))),
    primary key (id)
);

create table leave_balances (
    allocated_leaves integer not null,
    expired_leaves integer not null,
    remaining_leaves integer not null,
    used_leaves integer not null,
    year integer not null,
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    leave_type_id bigint not null,
    updated_at timestamp(6),
    primary key (id),
    unique (employee_id, leave_type_id, year)
);

create table leave_requests (
    end_date date not null,
    start_date date not null,
    total_days integer not null,
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    leave_type_id bigint not null,
    updated_at timestamp(6),
    status varchar(30) not null check ((status in ('PENDING','REJECTED','APPROVED','CANCELLED'))),
    reason varchar(500) not null,
    primary key (id)
);

create table leave_settings (
    active boolean not null,
    annual_paid_leave integer not null,
    carry_forward_allowed boolean not null,
    monthly_guideline integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    primary key (id)
);

create table leave_transactions (
    balance_after integer not null,
    balance_before integer not null,
    days integer not null,
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    leave_request_id bigint,
    leave_type_id bigint not null,
    updated_at timestamp(6),
    remarks varchar(500),
    transaction_type varchar(255) not null check ((transaction_type in ('ALLOCATION','LEAVE_APPROVED','LEAVE_CANCELLED','HR_ADJUSTMENT','CARRY_FORWARD','EXPIRED','EXPIRY','ALLOCATION_ADJUSTED'))),
    primary key (id)
);

create table leave_types (
    active boolean not null,
    allocated_days integer not null,
    carry_forward_allowed boolean not null,
    monthly_guideline integer not null,
    paid boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    name varchar(50) not null,
    description varchar(255),
    primary key (id),
    unique (name)
);

create table notifications (
    is_read boolean not null,
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    reference_id bigint,
    updated_at timestamp(6),
    priority varchar(20) not null check ((priority in ('LOW','MEDIUM','HIGH'))),
    notification_type varchar(30) not null check ((notification_type in ('LEAVE_APPLIED','LEAVE_MANAGER_APPROVED','LEAVE_HR_APPROVED','LEAVE_REJECTED','LEAVE_CANCELLED','LATE_CHECK_IN','ABSENT','MISSED_CHECKOUT','CHECKOUT_REMINDER','HOLIDAY','BIRTHDAY','WORK_ANNIVERSARY','ANNOUNCEMENT','APPROVED','GENERAL'))),
    reference_type varchar(30) check ((reference_type in ('LEAVE','ATTENDANCE','HOLIDAY','EMPLOYEE','ANNOUNCEMENT','GENERAL'))),
    title varchar(150) not null,
    message varchar(1000) not null,
    primary key (id)
);

create table password_reset_tokens (
    expires_at timestamp(6) not null,
    id bigint generated by default as identity,
    used_at timestamp(6),
    user_id bigint not null,
    token_hash varchar(64) not null unique,
    primary key (id)
);

create table payroll_history (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    payroll_id bigint not null,
    performed_by bigint,
    updated_at timestamp(6),
    action varchar(30) not null check ((action in ('GENERATED','UPDATED','REGENERATED','APPROVED','PAID','SUPERSEDED','CANCELLED'))),
    remarks varchar(500),
    primary key (id)
);

create table payrolls (
    active boolean not null,
    approved_date date,
    basic_salary numeric(12,2) not null,
    bonus numeric(12,2) not null,
    date_of_joining date,
    esi numeric(12,2) not null,
    gross_salary numeric(12,2) not null,
    hra numeric(12,2) not null,
    income_tax numeric(12,2) not null,
    lop_amount numeric(12,2) not null,
    lop_days integer not null,
    medical_allowance numeric(12,2) not null,
    net_payable numeric(12,2) not null,
    other_allowance numeric(12,2) not null,
    other_deduction numeric(12,2) not null,
    payable_days integer not null,
    payment_date date,
    payroll_month date not null,
    pf numeric(12,2) not null,
    professional_tax numeric(12,2) not null,
    special_allowance numeric(12,2) not null,
    total_deduction numeric(12,2) not null,
    total_working_days integer not null,
    travel_allowance numeric(12,2) not null,
    version integer not null,
    worked_days integer not null,
    approved_by bigint,
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    salary_structure_id bigint not null,
    updated_at timestamp(6),
    ifsc_code varchar(20),
    pan_number varchar(20),
    status varchar(20) not null check ((status in ('DRAFT','GENERATED','APPROVED','PAID','SUPERSEDED','CANCELLED'))),
    uan varchar(20),
    account_number varchar(30),
    employee_code varchar(30) not null,
    payroll_number varchar(30) not null unique,
    bank_name varchar(100),
    department_name varchar(100),
    designation_name varchar(100),
    employee_name varchar(100) not null,
    payment_reference varchar(100),
    remarks varchar(500),
    primary key (id)
);

create table performance_reviews (
    review_month integer,
    review_year integer not null,
    score float(53) not null,
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    review_date timestamp(6) not null,
    reviewer_id bigint,
    updated_at timestamp(6),
    review_type varchar(20) not null check ((review_type in ('MONTHLY','YEARLY'))),
    status varchar(20) not null check ((status in ('DRAFT','COMPLETED'))),
    rating varchar(30) not null check ((rating in ('EXCELLENT','VERY_GOOD','GOOD','AVERAGE','NEEDS_IMPROVEMENT'))),
    improvements varchar(1000),
    strengths varchar(1000),
    employee_comment varchar(2000),
    manager_feedback varchar(2000),
    primary key (id),
    constraint uk_employee_review_period unique (employee_id, review_type, review_month, review_year)
);

create table refresh_tokens (
    revoked boolean not null,
    created_at timestamp(6) not null,
    expiry_date timestamp(6) not null,
    id bigint generated by default as identity,
    revoked_at timestamp(6),
    updated_at timestamp(6),
    user_id bigint not null,
    token varchar(255) not null unique,
    primary key (id)
);

create table revoked_tokens (
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    token varchar(255) not null unique,
    primary key (id)
);

create table salary_structures (
    basic_salary numeric(12,2) not null,
    bonus numeric(12,2) not null,
    effective_from date not null,
    effective_to date,
    esi numeric(12,2) not null,
    gross_salary numeric(12,2) not null,
    hra numeric(12,2) not null,
    income_tax numeric(12,2) not null,
    medical_allowance numeric(12,2) not null,
    net_salary numeric(12,2) not null,
    other_allowance numeric(12,2) not null,
    other_deduction numeric(12,2) not null,
    pf numeric(12,2) not null,
    professional_tax numeric(12,2) not null,
    special_allowance numeric(12,2) not null,
    travel_allowance numeric(12,2) not null,
    created_at timestamp(6) not null,
    employee_id bigint not null,
    id bigint generated by default as identity,
    salary_template_id bigint,
    updated_at timestamp(6),
    status varchar(20) not null check ((status in ('ACTIVE','INACTIVE'))),
    remarks varchar(500),
    primary key (id)
);

create table salary_templates (
    active boolean not null,
    basic_salary numeric(12,2) not null,
    bonus numeric(12,2) not null,
    esi numeric(12,2) not null,
    gross_salary numeric(12,2) not null,
    hra numeric(12,2) not null,
    income_tax numeric(12,2) not null,
    medical_allowance numeric(12,2) not null,
    other_allowance numeric(12,2) not null,
    other_deduction numeric(12,2) not null,
    pf numeric(12,2) not null,
    professional_tax numeric(12,2) not null,
    special_allowance numeric(12,2) not null,
    travel_allowance numeric(12,2) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    employee_type varchar(30) not null check ((employee_type in ('FULL_TIME','PART_TIME','CONTRACT','INTERN'))),
    primary key (id),
    constraint uk_salary_template_employee_type unique (employee_type)
);

create table users (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    last_login timestamp(6),
    password_changed_at timestamp(6),
    updated_at timestamp(6),
    role varchar(30) not null check ((role in ('SUPER_ADMIN','HR_ADMIN','MANAGER','EMPLOYEE','PAYROLL_ADMIN','CLIENT'))),
    user_status varchar(30) not null check ((user_status in ('ACTIVE','INACTIVE','LOCKED','DISABLED','PASSWORD_EXPIRED'))),
    username varchar(50) not null,
    email varchar(100) not null,
    password varchar(255) not null,
    primary key (id)
);

create index idx_payroll_employee 
   on payrolls (employee_id);

create index idx_payroll_month 
   on payrolls (payroll_month);

create index idx_payroll_status 
   on payrolls (status);

create index idx_payroll_active 
   on payrolls (active);

create index idx_salary_structure_employee 
   on salary_structures (employee_id);

create index idx_salary_structure_status 
   on salary_structures (status);

create index idx_salary_structure_effective_from 
   on salary_structures (effective_from);

alter table if exists announcement_attachment_urls 
   add constraint FK5c7iatlf2g304xrgye5p3t5p7 
   foreign key (announcement_id) 
   references announcements;

alter table if exists attendance 
   add constraint FKb48lmkou5j4rvde9sr88bqgjw 
   foreign key (employee_id) 
   references employees;

alter table if exists attendance_breaks 
   add constraint FKg291224fnv3ufx1tff864sy9g 
   foreign key (attendance_id) 
   references attendance;

alter table if exists attendance_regularization 
   add constraint FKcjir0dl7fhgmrc8grn4ilgdnu 
   foreign key (approved_by) 
   references employees;

alter table if exists attendance_regularization 
   add constraint FKgo7sdiiacwdnd8my6j5jieh19 
   foreign key (employee_id) 
   references employees;

alter table if exists attendance_regularization 
   add constraint FK1yj6x7ppiiue5gjr6tpvsvcrs 
   foreign key (rejected_by) 
   references employees;

alter table if exists attendance_regularization_detail 
   add constraint FKcnblfs07d82xqbkdwac1iuupb 
   foreign key (attendance_id) 
   references attendance;

alter table if exists attendance_regularization_detail 
   add constraint FKmcnca0ilfdgqjh4rpjjon4gs7 
   foreign key (regularization_id) 
   references attendance_regularization;

alter table if exists designations 
   add constraint FK5kgb0o61xcwqr3scbtopsca3p 
   foreign key (department_id) 
   references departments;

alter table if exists employee_payment_details 
   add constraint fk_employee_payment_details_employee 
   foreign key (employee_id) 
   references employees;

alter table if exists employees 
   add constraint FKgy4qe3dnqrm3ktd76sxp7n4c2 
   foreign key (department_id) 
   references departments;

alter table if exists employees 
   add constraint FKe4i9i8vu1j96m71g4v98kqirb 
   foreign key (designation_id) 
   references designations;

alter table if exists employees 
   add constraint FKiftfevnnkbty768nwfa4nsea8 
   foreign key (job_title_id) 
   references job_titles;

alter table if exists employees 
   add constraint FKj5dawmyfw3dmtixnsrr6cbk63 
   foreign key (reporting_manager_id) 
   references employees;

alter table if exists employees 
   add constraint FK69x3vjuy1t5p18a5llb8h2fjx 
   foreign key (user_id) 
   references users;

alter table if exists job_titles 
   add constraint FK1llxweoflk6kfdt63s3obwop3 
   foreign key (designation_id) 
   references designations;

alter table if exists leave_approvals 
   add constraint FKgt93wecxswqbgllpedgl52r3v 
   foreign key (approved_by) 
   references employees;

alter table if exists leave_approvals 
   add constraint FKbsm9akluxkbu71cryx0hf72fw 
   foreign key (leave_request_id) 
   references leave_requests;

alter table if exists leave_balances 
   add constraint FKmvepkwsegu6bt3ps5rfh1dx92 
   foreign key (employee_id) 
   references employees;

alter table if exists leave_balances 
   add constraint FK86791wotycqa54js45s9396wy 
   foreign key (leave_type_id) 
   references leave_types;

alter table if exists leave_requests 
   add constraint FKrxff2xg1kffbjfh5maxwoqyhw 
   foreign key (employee_id) 
   references employees;

alter table if exists leave_requests 
   add constraint FK26il0qrl79p6etqwn0ae6l43b 
   foreign key (leave_type_id) 
   references leave_types;

alter table if exists leave_transactions 
   add constraint FKotalnbfw6gv8xgwrjiswj90rq 
   foreign key (employee_id) 
   references employees;

alter table if exists leave_transactions 
   add constraint FK3cydhld41pqwhtbfr1q0sjbf8 
   foreign key (leave_request_id) 
   references leave_requests;

alter table if exists leave_transactions 
   add constraint FKl4witanecbbf9uocdkgikfotv 
   foreign key (leave_type_id) 
   references leave_types;

alter table if exists notifications 
   add constraint FKt73pmdga1salintddb9hn6es9 
   foreign key (employee_id) 
   references employees;

alter table if exists password_reset_tokens 
   add constraint FKk3ndxg5xp6v7wd4gjyusp15gq 
   foreign key (user_id) 
   references users;

alter table if exists payroll_history 
   add constraint fk_payroll_history_payroll 
   foreign key (payroll_id) 
   references payrolls;

alter table if exists payroll_history 
   add constraint fk_payroll_history_employee 
   foreign key (performed_by) 
   references employees;

alter table if exists payrolls 
   add constraint fk_payroll_approved_by 
   foreign key (approved_by) 
   references employees;

alter table if exists payrolls 
   add constraint fk_payroll_employee 
   foreign key (employee_id) 
   references employees;

alter table if exists payrolls 
   add constraint fk_payroll_salary_structure 
   foreign key (salary_structure_id) 
   references salary_structures;

alter table if exists performance_reviews 
   add constraint FK75f19q3rvitsw5bl5o3k0lirt 
   foreign key (employee_id) 
   references employees;

alter table if exists performance_reviews 
   add constraint FK57bxpu5rccy6vvcqolbnbqal0 
   foreign key (reviewer_id) 
   references employees;

alter table if exists refresh_tokens 
   add constraint fk_refresh_token_user 
   foreign key (user_id) 
   references users;

alter table if exists salary_structures 
   add constraint fk_salary_structure_employee 
   foreign key (employee_id) 
   references employees;

alter table if exists salary_structures 
   add constraint fk_salary_structure_template 
   foreign key (salary_template_id) 
   references salary_templates;
