-- =====================================================================
-- V5 - Form 16 table suite
-- =====================================================================
-- The form_16 and Form_16A modules (10 entities) shipped without any
-- migration. They were only ever created in development by
-- spring.jpa.hibernate.ddl-auto=update, so V1 never contained them.
--
-- On a brand-new database that means Flyway finishes at V4 and Hibernate
-- then aborts startup with:
--
--     SchemaManagementException: Schema validation: missing table [form16]
--
-- because every profile runs ddl-auto=validate. DigitalOcean Managed
-- PostgreSQL starts empty, so this migration is what makes a first
-- production boot possible.
--
-- Column definitions are exactly what Hibernate 7.2 generates for these
-- entities (captured from the schema-generation script), so the tables
-- validate cleanly.
--
-- Every statement is idempotent: databases that already created these
-- tables through ddl-auto=update are skipped rather than failing, and
-- foreign keys are added only when missing - ddl-auto=update logs
-- constraint failures as warnings, so they may not have been created.
--
-- Never edit an applied migration. Add V6, V7, ... for further changes.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Parent table: one certificate per employee per assessment year.
-- Child tables are created after it because they reference it.
-- ---------------------------------------------------------------------

create table if not exists form16 (
    active boolean not null,
    employment_from date,
    employment_to date,
    last_updated_on date not null,
    opting_out_115bac_1a boolean,
    certificate_no varchar(8) not null unique,
    employee_id bigint not null,
    id bigint generated by default as identity,
    assessment_year varchar(20) not null,
    deductor_pan varchar(20),
    deductor_tan varchar(20),
    employee_pan varchar(20),
    employer_phone varchar(20),
    employer_email varchar(150),
    employer_name varchar(200),
    cit_tds_address varchar(2000),
    employee_address varchar(2000),
    employer_address varchar(2000),
    primary key (id),
    constraint uk_form16_employee_assessment_year unique (employee_id, assessment_year)
);


-- ---------------------------------------------------------------------
-- Part A / Part B child tables, each one-to-one with form16.
-- ---------------------------------------------------------------------

create table if not exists form16_challan (
    serial_number integer not null,
    tax_deposited numeric(15, 2) not null,
    tax_deposited_date date,
    form16_id bigint not null,
    id bigint generated by default as identity,
    status_of_matching_with_oltas varchar(20),
    bsr_code varchar(50),
    challan_serial_number varchar(100),
    primary key (id)
);

create table if not exists form16_chapter_via (
    amount_deductible_under_any_other_provision_chapter_via numeric(15, 2) not null,
    other_chapter_via numeric(15, 2) not null,
    section_80c numeric(15, 2) not null,
    section_80ccc numeric(15, 2) not null,
    section_80ccd_1 numeric(15, 2) not null,
    section_80ccd_1b numeric(15, 2) not null,
    section_80ccd_2 numeric(15, 2) not null,
    section_80cch numeric(15, 2) not null,
    section_80cch2 numeric(15, 2) not null,
    section_80d numeric(15, 2) not null,
    section_80e numeric(15, 2) not null,
    section_80eea numeric(15, 2) not null,
    section_80g numeric(15, 2) not null,
    section_80gg numeric(15, 2) not null,
    section_80tta numeric(15, 2) not null,
    section_80ttb numeric(15, 2) not null,
    total_chapter_via numeric(15, 2) not null,
    total_deduction_80c_80ccc_80ccd1 numeric(15, 2) not null,
    total_taxable_income numeric(15, 2) not null,
    form16_id bigint not null unique,
    id bigint generated by default as identity,
    primary key (id)
);

create table if not exists form16_exemption (
    other_section_10 numeric(15, 2) not null,
    section_10_10 numeric(15, 2) not null,
    section_10_10a numeric(15, 2) not null,
    section_10_10aa numeric(15, 2) not null,
    section_10_10b numeric(15, 2) not null,
    section_10_13a numeric(15, 2) not null,
    section_10_5 numeric(15, 2) not null,
    total_exemption numeric(15, 2) not null,
    total_salary_received_current_employer numeric(15, 2) not null,
    form16_id bigint not null unique,
    id bigint generated by default as identity,
    primary key (id)
);

create table if not exists form16_last_fields (
    health_and_education_cess numeric(15, 2) not null,
    net_tax_payable numeric(15, 2) not null,
    rebate_under_section_87a numeric(15, 2) not null,
    relief_under_section_89 numeric(15, 2) not null,
    surcharge numeric(15, 2) not null,
    tax_collected_at_source_form_12baa numeric(15, 2) not null,
    tax_deducted_at_source_form_12baa numeric(15, 2) not null,
    tax_on_total_income numeric(15, 2) not null,
    tax_payable numeric(15, 2) not null,
    form16_id bigint not null unique,
    id bigint generated by default as identity,
    primary key (id)
);

create table if not exists form16_quarter (
    book_adjustment_serial_number integer,
    book_adjustment_tax_deposited numeric(15, 2),
    date_of_transfer_voucher date,
    q1_amount_paid_credited numeric(15, 2) not null,
    q1_tax_deducted numeric(15, 2) not null,
    q1_tax_deposited_remitted numeric(15, 2) not null,
    q2_amount_paid_credited numeric(15, 2) not null,
    q2_tax_deducted numeric(15, 2) not null,
    q2_tax_deposited_remitted numeric(15, 2) not null,
    q3_amount_paid_credited numeric(15, 2) not null,
    q3_tax_deducted numeric(15, 2) not null,
    q3_tax_deposited_remitted numeric(15, 2) not null,
    q4_amount_paid_credited numeric(15, 2) not null,
    q4_tax_deducted numeric(15, 2) not null,
    q4_tax_deposited_remitted numeric(15, 2) not null,
    total_amount_paid_credited numeric(15, 2) not null,
    total_book_adjustment_tax_deposited numeric(15, 2) not null,
    total_tax_deducted numeric(15, 2) not null,
    total_tax_deposited_remitted numeric(15, 2) not null,
    form16_id bigint not null unique,
    id bigint generated by default as identity,
    ddo_serial_number_form_24g varchar(100),
    q1_receipt_number varchar(100) not null unique,
    q2_receipt_number varchar(100) not null unique,
    q3_receipt_number varchar(100) not null unique,
    q4_receipt_number varchar(100) not null unique,
    receipt_number_form_24g varchar(100),
    status_of_matching_with_form_24g varchar(100),
    primary key (id)
);

create table if not exists form16_salary (
    gross_salary numeric(15, 2) not null,
    perquisites_u_s_17_2 numeric(15, 2) not null,
    profits_in_lieu_u_s_17_3 numeric(15, 2) not null,
    salary_received_from_other_employers numeric(15, 2) not null,
    salary_u_s_17_1 numeric(15, 2) not null,
    form16_id bigint not null unique,
    id bigint generated by default as identity,
    primary key (id)
);

create table if not exists form16_section16_deduction (
    entertainment_allowance_section_16_ii numeric(15, 2) not null,
    gross_total_income numeric(15, 2) not null,
    income_chargeable_under_salaries numeric(15, 2) not null,
    income_loss_house_property numeric(15, 2) not null,
    income_under_other_sources numeric(15, 2) not null,
    salary_received_from_current_employer numeric(15, 2) not null,
    salary_received_from_other_employers numeric(15, 2) not null,
    standard_deduction_section_16_i numeric(15, 2) not null,
    tax_on_employment_section_16_iii numeric(15, 2) not null,
    total_deductions_section_16 numeric(15, 2) not null,
    total_other_income numeric(15, 2) not null,
    form16_id bigint not null unique,
    id bigint generated by default as identity,
    primary key (id)
);

create table if not exists form16_verification (
    verification_date date,
    form16_id bigint not null unique,
    id bigint generated by default as identity,
    designation varchar(200),
    place varchar(200),
    full_name varchar(300),
    signature varchar(500),
    primary key (id)
);


-- ---------------------------------------------------------------------
-- Employer master (standalone, no FK)
-- ---------------------------------------------------------------------

create table if not exists form16_employer_master (
    active boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    deductor_pan varchar(10) not null,
    deductor_tan varchar(10) not null,
    employer_phone varchar(20),
    employer_email varchar(150),
    employer_name varchar(200) not null,
    cit_tds_address varchar(2000) not null,
    employer_address varchar(2000) not null,
    primary key (id)
);


create index if not exists idx_form16_challan_form16
    on form16_challan (form16_id);


-- ---------------------------------------------------------------------
-- Foreign keys.
--
-- Added separately, and only when absent, so that databases where
-- ddl-auto=update silently skipped them end up with the same constraints
-- as a database created from scratch.
-- ---------------------------------------------------------------------

do $$
declare
    fk record;
begin
    for fk in
        select *
          from (values
                ('form16',                     'fk_form16_employee',
                 'employee_id',                'employees'),
                ('form16_challan',             'fk_form16_challan_form16',
                 'form16_id',                  'form16'),
                ('form16_chapter_via',         'fk_form16_chapter_via_form16',
                 'form16_id',                  'form16'),
                ('form16_exemption',           'fk_form16_exemption_form16',
                 'form16_id',                  'form16'),
                ('form16_last_fields',         'fk_form16_last_fields_form16',
                 'form16_id',                  'form16'),
                ('form16_quarter',             'fk_form16_quarter_form16',
                 'form16_id',                  'form16'),
                ('form16_salary',              'fk_form16_salary_form16',
                 'form16_id',                  'form16'),
                ('form16_section16_deduction', 'fk_form16_section16_deduction_form16',
                 'form16_id',                  'form16'),
                ('form16_verification',        'fk_form16_verification_form16',
                 'form16_id',                  'form16')
               ) as t(table_name, constraint_name, column_name, referenced_table)
    loop
        if not exists (
            select 1
              from pg_constraint
             where conname = fk.constraint_name
               and conrelid = to_regclass(fk.table_name)
        ) then
            execute format(
                'alter table %I add constraint %I foreign key (%I) references %I',
                fk.table_name, fk.constraint_name, fk.column_name, fk.referenced_table
            );
        end if;
    end loop;
end $$;
