package com.my_hourly.settings.workLogs.dto.response;

// DISABLED: part of the unused workLogs settings submodule (see WorkLogSettings).
//
//import jakarta.validation.constraints.NotNull;
//import lombok.*;
//
//import java.time.LocalTime;
//
//@Getter
//@Setter
//@Builder
//@NoArgsConstructor
//@AllArgsConstructor
//public class WorkLogSettingsResponse {
//
//    private Long id;
//
//    private Boolean workLogSubmissionRequired;
//
//    private Boolean reportRequiredBeforeCheckout;
//
//    private LocalTime reportSubmissionDeadline;
//
//    private Integer minimumWorkLogEntries;
//
//    private Boolean workLogReminderEnabled;
//
//    private Integer reminderIntervalMinutes;
//
//    private Boolean managerEmailNotification;
//
//    private Boolean employeePdfDownloadAllowed;
//
//    private Boolean managerApprovalRequired;
//
//    private Boolean allowWorkLogEditAfterSubmission;
//
//    private Boolean autoGenerateDailySummary;
//
//    private Integer minimumWorkLogDescriptionLength;
//
//    private Boolean allowMultipleReportSubmissionsPerDay;
//
//    private Boolean active;
//
//}
